// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore.Models;

#nullable disable

namespace TechStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326081828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TechStore.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TechStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Máy tính xách tay",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Máy tính để bàn",
                            Name = "PC / Desktop"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Monitor các loại",
                            Name = "Màn hình"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bàn phím, chuột, tai nghe",
                            Name = "Phụ kiện"
                        },
                        new
                        {
                            Id = 5,
                            Description = "CPU, RAM, SSD, VGA",
                            Name = "Linh kiện"
                        });
                });

            modelBuilder.Entity("TechStore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TechStore.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TechStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Core i5-1235U, RAM 8GB DDR4, SSD 512GB NVMe, 15.6\" FHD IPS, Iris Xe, Win 11",
                            ImageUrl = "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=400&q=80",
                            Name = "Laptop ASUS VivoBook 15 X1504ZA",
                            Price = 14990000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Core i5-1235U, RAM 16GB DDR4, SSD 512GB, 15.6\" FHD, Win 11 Home",
                            ImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80",
                            Name = "Laptop Dell Inspiron 15 3520",
                            Price = 16490000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Core i7-1355U, RAM 16GB, SSD 512GB, GeForce RTX 2050 4GB, 15.6\" FHD IPS",
                            ImageUrl = "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&q=80",
                            Name = "Laptop HP Pavilion 15-eg3097TX",
                            Price = 18990000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Ryzen 7 6800H, RAM 16GB, SSD 512GB, Radeon RX 6600M, 16\" 2.5K 120Hz",
                            ImageUrl = "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&q=80",
                            Name = "Laptop Lenovo IdeaPad 5 Pro 16ARH7",
                            Price = 21490000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Apple M2 8-core, RAM 8GB Unified, SSD 256GB, 13.6\" Liquid Retina, macOS",
                            ImageUrl = "https://images.unsplash.com/photo-1611186871525-b6a9b7b3a4f4?w=400&q=80",
                            Name = "Laptop MacBook Air M2 13\"",
                            Price = 27990000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Core i9-14900HX, RTX 4070 8GB, RAM 32GB DDR5, SSD 1TB, 16\" QHD 240Hz",
                            ImageUrl = "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400&q=80",
                            Name = "Laptop ASUS ROG Strix G16 2024",
                            Price = 42990000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Core i5-12500H, RTX 3050 4GB, RAM 8GB, SSD 512GB, 15.6\" FHD 144Hz",
                            ImageUrl = "https://images.unsplash.com/photo-1580927752452-89d86da3fa0a?w=400&q=80",
                            Name = "Laptop Acer Nitro 5 AN515-58",
                            Price = 19990000m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Core i7-12650H, RTX 4050 6GB, RAM 16GB, SSD 512GB, 15.6\" FHD 144Hz",
                            ImageUrl = "https://images.unsplash.com/photo-1547082299-de196ea013d6?w=400&q=80",
                            Name = "Laptop MSI Thin GF63 12VE",
                            Price = 22490000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Core i7-13700F, RTX 4060 8GB, RAM 16GB DDR5, SSD 1TB NVMe, Case ATX Full RGB",
                            ImageUrl = "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=400&q=80",
                            Name = "PC Gaming RGB i7 RTX 4060",
                            Price = 28900000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Ryzen 9 7900X, RTX 4070 Ti 12GB, RAM 32GB DDR5, SSD 2TB, Cooler Noctua NH-D15",
                            ImageUrl = "https://images.unsplash.com/photo-1520659649-1b4f85f5cfc0?w=400&q=80",
                            Name = "PC Workstation Ryzen 9 Pro",
                            Price = 38500000m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Core i5-1340P, RAM 16GB LPDDR5, SSD 512GB, Thunderbolt 4, WiFi 6E, BT 5.3",
                            ImageUrl = "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80",
                            Name = "Mini PC Intel NUC 13 Pro",
                            Price = 11990000m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Core i3-12100, RAM 8GB DDR4, SSD 256GB, Case mATX, Tặng bàn phím + chuột",
                            ImageUrl = "https://images.unsplash.com/photo-1593640408182-31c228f1e97e?w=400&q=80",
                            Name = "PC Văn phòng Intel Core i3 Budget",
                            Price = 8490000m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "27\", 4K UHD 3840x2160, IPS, 60Hz, HDR400, USB-C 60W, sRGB 99%",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&q=80",
                            Name = "Màn hình LG 27\" 4K IPS UltraFine",
                            Price = 8990000m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "32\", QHD 2560x1440, VA Curved, 165Hz, 1ms MPRT, FreeSync Premium",
                            ImageUrl = "https://images.unsplash.com/photo-1586210579191-33b45e38fa2c?w=400&q=80",
                            Name = "Màn hình Samsung 32\" Odyssey G5",
                            Price = 7490000m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "27\", FHD IPS, 240Hz, 1ms GTG, G-Sync Compatible, HDR10, USB Hub",
                            ImageUrl = "https://images.unsplash.com/photo-1551645120-d70bfe84c826?w=400&q=80",
                            Name = "Màn hình ASUS ROG Swift 27\" 240Hz",
                            Price = 12990000m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "24\", FHD 1920x1080, IPS, 75Hz, 4ms, FreeSync, VGA+HDMI, Frameless",
                            ImageUrl = "https://images.unsplash.com/photo-1616763355548-1b606f439f86?w=400&q=80",
                            Name = "Màn hình AOC 24\" FHD 75Hz",
                            Price = 2990000m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "75%, Hot-swap, RGB backlit, Gateron Brown switch, Bluetooth 5.1 + USB-C",
                            ImageUrl = "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?w=400&q=80",
                            Name = "Bàn phím cơ Keychron K2 V2",
                            Price = 2290000m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "LIGHTFORCE hybrid switch, HERO 25K sensor, 25,600 DPI, 13 nút, sạc không dây",
                            ImageUrl = "https://images.unsplash.com/photo-1527814050087-3793815479db?w=400&q=80",
                            Name = "Chuột gaming Logitech G502 X Plus",
                            Price = 2890000m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Chống ồn ANC hàng đầu, 30h pin, LDAC Hi-Res, Multipoint, gập gọn",
                            ImageUrl = "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&q=80",
                            Name = "Tai nghe Sony WH-1000XM5",
                            Price = 8990000m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Driver kép 50mm, mic tháo rời, âm thanh vòm 7.1, tương thích PC/PS/Xbox",
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
                            Name = "Tai nghe gaming HyperX Cloud Alpha",
                            Price = 1990000m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Full HD 1080p/30fps, autofocus, mic kép, tích hợp, clip gắn màn hình",
                            ImageUrl = "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400&q=80",
                            Name = "Webcam Logitech C920 HD Pro",
                            Price = 1690000m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "HDMI 4K, USB-A 3.0 x2, USB-C PD 100W, SD/microSD, tương thích MacBook/Win",
                            ImageUrl = "https://images.unsplash.com/photo-1625948515291-69613efd103f?w=400&q=80",
                            Name = "Bộ hub USB-C 7-in-1 Anker",
                            Price = 890000m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Description = "PCIe 4.0 x4, Read 7,000MB/s, Write 5,000MB/s, TLC V-NAND, tản nhiệt",
                            ImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
                            Name = "SSD Samsung 980 Pro 1TB NVMe M.2",
                            Price = 2790000m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Description = "DDR5-5200MHz, 32GB (2x16GB), CL40, Intel XMP 3.0 & AMD EXPO, tản RGB",
                            ImageUrl = "https://images.unsplash.com/photo-1541029071515-84cc54f84dc5?w=400&q=80",
                            Name = "RAM DDR5 Kingston Fury Beast 32GB",
                            Price = 2490000m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Description = "16 nhân (8P+8E) / 24 luồng, Boost 5.4GHz, L3 30MB, TDP 125W, socket LGA1700",
                            ImageUrl = "https://images.unsplash.com/photo-1591799265444-d66432b91588?w=400&q=80",
                            Name = "CPU Intel Core i7-13700K",
                            Price = 8990000m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Description = "6 nhân / 12 luồng, Boost 5.3GHz, L3 32MB, TDP 105W, PCIe 5.0, AM5",
                            ImageUrl = "https://images.unsplash.com/photo-1555617981-dac3880eac6e?w=400&q=80",
                            Name = "CPU AMD Ryzen 5 7600X",
                            Price = 5490000m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            Description = "12GB GDDR6X, 192-bit, DLSS 3, Ray Tracing, 2505MHz Boost, 2x HDMI 2.1, 3x DP",
                            ImageUrl = "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=400&q=80",
                            Name = "VGA ASUS GeForce RTX 4070 12GB DUAL",
                            Price = 16990000m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            Description = "Intel B760, LGA1700, DDR5, PCIe 4.0, WiFi 6E, BT 5.3, 2x M.2, mATX",
                            ImageUrl = "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80",
                            Name = "Mainboard MSI MAG B760M Mortar WiFi",
                            Price = 3990000m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            Description = "850W, 80+ Gold, Full Modular, 10 năm bảo hành, Zero RPM fan, ATX 3.0",
                            ImageUrl = "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&q=80",
                            Name = "Nguồn Corsair RM850x 850W 80+ Gold",
                            Price = 2990000m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            Description = "Radiator 240mm, 2x fan 120mm PWM, LCD màn hình hiển thị, ARGB, socket AM5/1700",
                            ImageUrl = "https://images.unsplash.com/photo-1560732488-6b0df240254a?w=400&q=80",
                            Name = "Tản nhiệt nước AIO NZXT Kraken 240",
                            Price = 2690000m
                        });
                });

            modelBuilder.Entity("TechStore.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("TechStore.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TechStore.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TECHSTORE10",
                            DiscountPercent = 10,
                            ExpiryDate = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UsageLimit = 1000,
                            UsedCount = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "SALE20",
                            DiscountPercent = 20,
                            ExpiryDate = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UsageLimit = 100,
                            UsedCount = 0
                        },
                        new
                        {
                            Id = 3,
                            Code = "NEWUSER15",
                            DiscountPercent = 15,
                            ExpiryDate = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UsageLimit = 500,
                            UsedCount = 0
                        },
                        new
                        {
                            Id = 4,
                            Code = "GAMING30",
                            DiscountPercent = 30,
                            ExpiryDate = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UsageLimit = 50,
                            UsedCount = 0
                        },
                        new
                        {
                            Id = 5,
                            Code = "LINH5",
                            DiscountPercent = 5,
                            ExpiryDate = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UsageLimit = 999,
                            UsedCount = 0
                        });
                });

            modelBuilder.Entity("TechStore.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TechStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TechStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TechStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechStore.Models.Order", b =>
                {
                    b.HasOne("TechStore.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechStore.Models.OrderItem", b =>
                {
                    b.HasOne("TechStore.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechStore.Models.Product", b =>
                {
                    b.HasOne("TechStore.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechStore.Models.ProductImage", b =>
                {
                    b.HasOne("TechStore.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechStore.Models.Review", b =>
                {
                    b.HasOne("TechStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechStore.Models.WishlistItem", b =>
                {
                    b.HasOne("TechStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechStore.Models.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TechStore.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechStore.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TechStore.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
